### ISSUE TITLE
Crashing when Reloading

### ISSUE THREAD

**Issue by Mhmdjoudi** [Desno365/DesnoGuns-Mod#10]
Everytime i reload, blocklauncher crashes and closes the game please help

**Comment by Desno365** [comment]
I can't reproduce it. Can you try to update Blocklauncher and tell me again if it works?

**Comment by Mhmdjoudi** [comment]
It worked when i updated to 0.13.0 but now guns and knive dont kill anymore

**Comment by Mhmdjoudi** [comment]
It worked when i updated to 0.13.0 but now guns and knive dont kill anymore
