### ISSUE TITLE
Guns and knives dont kill

### ISSUE THREAD

**Issue by Mhmdjoudi** [Desno365/DesnoGuns-Mod#11]
I have a problem which is in my 0.13.0 build 4, the problem is that when i shoot any mob or stab with a knive, the mob doesnt die. I even tried to kill a mob with a macgine gun but it didnt die

**Comment by Desno365** [comment]
It's a bug of Minecraft, in some worlds items that are not tools can't hit mobs. I can't do anything to fix it :(
