### ISSUE TITLE
It don't work

### ISSUE THREAD

**Issue by S0CRAM** [Desno365/DesnoGuns-Mod#12]
The mod doesn't work when I imported it to block launcher pro and I always crash. The texture pack (both) actually work good so that's the only problem I have

**Comment by Desno365** [comment]
Probably you're using an old version of the DesnoGuns Mod, the r010 version crashes with MCPE 0.13.1. Just update the mod to r011 and it should work. If it doesn't report it to me. 
You can donwload the latest version form here http://desno365.net/minecraft/desnoguns-mod/

**Comment by S0CRAM** [comment]
I did but it still doesn't work im using the latest update
