### ISSUE TITLE
Pitch-Black Textures on addon

### ISSUE THREAD

**Issue by Spencer87** [Desno365/DesnoGuns-Mod#18]
Help, when I added a new gun to my addon and imported it the hold texture shows up but my inventory textures are pitch black! Please help:(

**Comment by Desno365** [comment]
I think it may be because you are making these textures with some level of transparency (also called alpha). But I'm not 100% sure, if you send me the textures and the addon I'll take a look at it

**Comment by Spencer87** [comment]
Here is the addon with pitch black textures:

http://www.mediafire.com/?sdccvs2fsseh47d

**Comment by Desno365** [comment]
It's because MCPE can't load 512x512 textures, they are too much big.
I think also 256x256 it's too much, you should use 128x128 max.
