### ISSUE TITLE
Crash because explode

### ISSUE THREAD

**Issue by XxAriCoolxX** [Desno365/DesnoGuns-Mod#20]
If i using grenade and crossbow explode it will be crash while explode. Plz fix the bug because i love this mod so much

**Comment by Desno365** [comment]
Thanks for reporting, the grenade bug it's a known bug and it's caused by Blocklauncher not yet fully updated. While I will investigate more the crossbow explosive bug.

**Comment by Desno365** [comment]
Fixed in r025.
