### ISSUE TITLE
Recoil?

### ISSUE THREAD

**Issue by InsydeH20** [Desno365/DesnoGuns-Mod#23]
So i installed the mod. When i fired the gun, there is recoil. That's normal, right? The problem is when i move while firing a gun, it will shake(?) the player around and at times, it would throw me up in the sky and fall back down, and that would kill me. I do not know what really causes this.
(Running version r025 on A7-2017)

**Comment by Desno365** [comment]
Thanks for the datailed report. Unfortunately it's a bug of Blocklauncher that I can't do anything about. If you would like you can report it to the Blocklauncher Github repository: https://github.com/zhuowei/MCPELauncher

The only thing I could do it's completely disable recoil but that would be counterproductive.

**Comment by paperbenni** [comment]
@Desno365 The last commit on there is from 2014, I don't really think that zuhowei is that active on the open source side.
