### ISSUE TITLE
Setting GUI

### ISSUE THREAD

**Issue by Linklies** [Desno365/DesnoGuns-Mod#4]
The settings page is not compatible with my device, my device is HTC_amaze_4G

**Comment by Desno365** [comment]
Have you updated the mod to r007? It should have been fixed in that version.

**Comment by Linklies** [comment]
I have

**Comment by Linklies** [comment]
Oh sorry seems like I thought it did't work

**Comment by Desno365** [comment]
So it works, right?
I'll close the issue, if there are any other problems I can reopen it.

**Comment by Linklies** [comment]
Yes it works , and by the way awesome mod you have worked on! Great job.
